# Generated by Django 3.1.6 on 2021-02-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210224_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='password',
            field=models.CharField(default='', max_length=16, verbose_name='비밀번호'),
        ),
    ]
