# Generated by Django 3.1.6 on 2021-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='제목'),
        ),
    ]
