# Generated by Django 3.1.6 on 2021-03-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210225_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='좋아요'),
        ),
        migrations.AddField(
            model_name='thread',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='노출 수'),
        ),
    ]
