# Generated by Django 3.1.6 on 2021-09-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210402_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='태그')),
                ('synonyms', models.TextField(default='', verbose_name='비슷한 태그')),
                ('associated_words', models.TextField(default='', verbose_name='연관 태그')),
            ],
        ),
        migrations.CreateModel(
            name='TagThreadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tagdictionary', verbose_name='태그')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.thread', verbose_name='게시물')),
            ],
        ),
    ]
