# Generated by Django 3.1.6 on 2021-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_tagdictionary_tagthreadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdictionary',
            name='hit_count',
            field=models.IntegerField(default=0, verbose_name='클릭 횟수'),
        ),
        migrations.AddField(
            model_name='tagdictionary',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='검색 횟수'),
        ),
    ]
