# Generated by Django 3.1.6 on 2021-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210909_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdictionary',
            name='register_count',
            field=models.IntegerField(default=0, verbose_name='등록 횟수'),
        ),
    ]
