# Generated by Django 3.1.6 on 2021-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_tagdictionary_register_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagdictionary',
            name='register_count',
            field=models.IntegerField(default=1, verbose_name='등록 횟수'),
        ),
    ]
