# Generated by Django 3.1.6 on 2021-09-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_likemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='like_count',
        ),
    ]
