# Generated by Django 3.1.6 on 2021-12-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_thread_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='password',
            field=models.CharField(default='', max_length=16, verbose_name='비밀번호'),
        ),
    ]
