# Generated by Django 3.1.6 on 2021-12-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_reply_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='nickname',
            field=models.CharField(default='', max_length=16, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.TextField(default='', max_length=300, verbose_name='답글'),
        ),
    ]
