# Generated by Django 3.1.6 on 2021-12-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20211207_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성여부'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성여부'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.TextField(default='', max_length=300, verbose_name='댓글'),
        ),
    ]
